# **************************************************************************** #
#                                                                              #
#    Host: e3r7p3.42roma.it                                           /_/      #
#    File: docker-compose.yml                                      ( o.o )     #
#    Created: 2025/07/13 15:14:40 | By: atucci <atucci@student.42  > ^ <       #
#    Updated: 2025/07/13 15:14:43                                   /          #
#    OS: Linux 6.5.0-44-generic x86_64 | CPU: Intel(R) Core(TM) i (|_|)_)      #
#                                                                              #
# **************************************************************************** #


