# **************************************************************************** #
#                                                                              #
#    Host: e3r7p3.42roma.it                                           /_/      #
#    File: docker-compose.yml                                      ( o.o )     #
#    Created: 2025/07/13 15:14:40 | By: atucci <atucci@student.42  > ^ <       #
#    Updated: 2025/07/13 18:15:16                                   /          #
#    OS: Linux 6.5.0-44-generic x86_64 | CPU: Intel(R) Core(TM) i (|_|)_)      #
#                                                                              #
# **************************************************************************** #

version: "3.9"

# Define all services needed for the mandatory part here
services:

# NGINX reverse proxy container
# - Should act as the single entry point (port 443 only)
# - Needs to use TLSv1.2 or TLSv1.3
# - Should proxy requests to WordPress
# - Must depend on WordPress and possibly MariaDB (indirectly)
# - Mount certificate files or secrets as needed

# WordPress container (PHP-FPM only, no web server)
# - Should serve PHP application logic for WordPress
# - Should connect to the database (MariaDB)
# - Should use environment variables for configuration
# - Mounts a volume for WordPress site files

# MariaDB container
# - Should store and serve the WordPress database
# - Requires secure credentials via environment or secrets
# - Mounts a volume for database persistence
# - Should initialize with proper user and password settings

# Define volumes (named) for persistence
# - One for WordPress files
# - One for WordPress database data

# Define a custom network
# - All containers must use the same internal bridge network
# - No use of "network: host" or deprecated "links"

# OPTIONAL: Redis cache service (bonus)
# - Used to improve WordPress performance
# - WordPress must be configured to use Redis

# OPTIONAL: FTP server (bonus)
# - Provides file transfer access to WordPress volume
# - Requires mounting the same volume as WordPress files

# OPTIONAL: Static website service (bonus)
# - Simple static web page (HTML, JS, CSS)
# - Could be served by a lightweight web server (e.g., nginx or httpd)

# OPTIONAL: Adminer (bonus)
# - Lightweight DB management interface
# - Should connect to the MariaDB container internally

# OPTIONAL: Your own service (bonus)
# - Justify its use and isolate it in a separate container
# - Follow same rules for volumes, env vars, and networks

# Define named volumes here
# - wordpress_db_data:
# - wordpress_site_data:

# Define custom networks here
# - app-network:

