version: '3'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:9.4
    volumes:
      - ./data:/var/lib/postgresql/data

