# **************************************************************************** #
#                                                                              #
#    Host: e3r7p3.42roma.it                                           /_/      #
#    File: Dockerfile                                              ( o.o )     #
#    Created: 2025/07/13 16:44:47 | By: atucci <atucci@student.42  > ^ <       #
#    Updated: 2025/07/17 10:25:28                                   /          #
#    OS: Linux 6.5.0-44-generic x86_64 | CPU: Intel(R) Core(TM) i (|_|)_)      #
#                                                                              #
# **************************************************************************** #

# Dockerfile for MariaDB
#TODO: remember that old stable point to the penultimate availabe!
FROM debian:oldstable

